apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-java-springboot-okitxaod
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/chetna14manku_org/backend-tests-java-springboot-okitxaod:e3c6a76d8501569567cd7d421dc13f6f99c40e7c
        name: container-image  
